export const departments = {
  roads: {
    id: "roads",
    name: "Roads & Infrastructure",
    icon: "🛣️",
    color: "#0ea5e9",
    subcategories: [
      "Potholes",
      "Damaged Roads",
      "Missing Signage",
      "Street Lights",
      "Footpath Issues",
      "Traffic Signals",
      "Road Markings",
      "Speed Breakers",
    ],
    departmentId: "PWD",
    contact: "1800-123-4567",
  },
  water: {
    id: "water",
    name: "Water & Sanitation",
    icon: "💧",
    color: "#14b8a6",
    subcategories: [
      "Water Leakage",
      "Sewage Blockage",
      "Contaminated Water",
      "Drainage Issues",
      "Water Supply",
      "Open Drains",
      "Manhole Cover Missing",
      "Flooding",
    ],
    departmentId: "WATER-BD",
    contact: "1800-123-4568",
  },
  electricity: {
    id: "electricity",
    name: "Electricity",
    icon: "⚡",
    color: "#eab308",
    subcategories: [
      "Power Outage",
      "Transformer Issue",
      "Faulty Meter",
      "Voltage Fluctuation",
      "Broken Wires",
      "Street Light Not Working",
      "Bill Related",
      "New Connection",
    ],
    departmentId: "ELEC-BD",
    contact: "1912",
  },
  environment: {
    id: "environment",
    name: "Environment",
    icon: "🌳",
    color: "#22c55e",
    subcategories: [
      "Garbage Dumping",
      "Air Pollution",
      "Tree Cutting",
      "Noise Pollution",
      "Illegal Construction",
      "Stagnant Water",
      "Mosquito Breeding",
      "Waste Burning",
    ],
    departmentId: "ENV-BD",
    contact: "1800-123-4569",
  },
} as const;

export type DepartmentId = keyof typeof departments;
